/**
 * 画布节点渲染元信息注册表。
 * 登记图标、布局、默认尺寸和最小尺寸。
 * 新增节点 UI 时先在这里注册，禁止继续扩大 CanvasCardRenderer.tsx 的 if-else 分支。
 */

import type { NodeType } from '../../../types/pebblingTypes';
import type { NodeRendererMeta } from '../types/canvas.types';

/**
 * 所有画布节点的渲染元信息注册表。
 * CanvasCardRenderer 通过此注册表查找渲染所需元数据，
 * 然后委托到各 feature 的节点 body 组件。
 */
export const NODE_RENDERER_REGISTRY: Partial<Record<NodeType, NodeRendererMeta>> = {
  text: {
    title: '文本',
    icon: 'Type',
    featureId: 'source-text',
    layout: 'standard',
    width: 320,
    height: 200,
    minWidth: 240,
    minHeight: 120,
    executable: true,
  },
  idea: {
    title: '创意',
    icon: 'Lightbulb',
    featureId: 'source-text',
    layout: 'standard',
    width: 320,
    height: 200,
    minWidth: 240,
    minHeight: 120,
    executable: true,
  },
  image: {
    title: '图片',
    icon: 'Image',
    featureId: 'source-media',
    layout: 'standard',
    width: 360,
    height: 300,
    minWidth: 200,
    minHeight: 180,
    executable: true,
  },
  video: {
    title: '视频',
    icon: 'Video',
    featureId: 'source-media',
    layout: 'standard',
    width: 360,
    height: 280,
    minWidth: 240,
    minHeight: 200,
    executable: true,
  },
  llm: {
    title: 'LLM 对话',
    icon: 'Brain',
    featureId: 'text-ai',
    layout: 'wide',
    width: 400,
    height: 440,
    minWidth: 320,
    minHeight: 280,
    executable: true,
  },
  output: {
    title: '输出素材',
    icon: 'Image',
    featureId: 'canvas',
    layout: 'standard',
    width: 360,
    height: 300,
    minWidth: 200,
    minHeight: 180,
    executable: false,
  },
  'video-output': {
    title: '视频输出',
    icon: 'Video',
    featureId: 'canvas',
    layout: 'standard',
    width: 360,
    height: 280,
    minWidth: 240,
    minHeight: 200,
    executable: false,
  },
  relay: {
    title: '中继',
    icon: 'ArrowLeftRight',
    featureId: 'canvas',
    layout: 'compact',
    width: 240,
    height: 100,
    minWidth: 180,
    minHeight: 80,
    executable: true,
  },
  runninghub: {
    title: 'RunningHub',
    icon: 'Zap',
    featureId: 'runninghub',
    layout: 'wide',
    width: 380,
    height: 360,
    minWidth: 300,
    minHeight: 240,
    executable: true,
  },
  'rh-main': {
    title: 'RH 主节点',
    icon: 'Star',
    featureId: 'runninghub',
    layout: 'compact',
    width: 300,
    height: 200,
    minWidth: 220,
    minHeight: 160,
    executable: false,
  },
  'rh-param': {
    title: 'RH 参数',
    icon: 'SlidersHorizontal',
    featureId: 'runninghub',
    layout: 'compact',
    width: 280,
    height: 140,
    minWidth: 200,
    minHeight: 100,
    executable: false,
  },
  'rh-config': {
    title: 'RH 配置',
    icon: 'Settings',
    featureId: 'runninghub',
    layout: 'standard',
    width: 340,
    height: 240,
    minWidth: 280,
    minHeight: 180,
    executable: false,
  },
  'drawing-board': {
    title: '画板',
    icon: 'Pencil',
    featureId: 'image-editing',
    layout: 'wide',
    width: 500,
    height: 420,
    minWidth: 320,
    minHeight: 280,
    executable: true,
  },
  edit: {
    title: '图片编辑',
    icon: 'Edit',
    featureId: 'image-editing',
    layout: 'standard',
    width: 360,
    height: 300,
    minWidth: 280,
    minHeight: 200,
    executable: true,
  },
  resize: {
    title: '调整尺寸',
    icon: 'Maximize2',
    featureId: 'image-editing',
    layout: 'compact',
    width: 300,
    height: 220,
    minWidth: 240,
    minHeight: 180,
    executable: true,
  },
  'remove-bg': {
    title: '移除背景',
    icon: 'Scissors',
    featureId: 'image-editing',
    layout: 'compact',
    width: 300,
    height: 200,
    minWidth: 240,
    minHeight: 160,
    executable: true,
  },
  upscale: {
    title: '图片放大',
    icon: 'ZoomIn',
    featureId: 'image-editing',
    layout: 'compact',
    width: 300,
    height: 220,
    minWidth: 240,
    minHeight: 180,
    executable: true,
  },
  'prompt-line': {
    title: '行选择',
    icon: 'List',
    featureId: 'source-text',
    layout: 'compact',
    width: 280,
    height: 160,
    minWidth: 200,
    minHeight: 120,
    executable: true,
  },
  'show-text': {
    title: '显示文本',
    icon: 'Eye',
    featureId: 'source-text',
    layout: 'standard',
    width: 300,
    height: 200,
    minWidth: 220,
    minHeight: 140,
    executable: true,
  },
  'replace-text': {
    title: '文本替换',
    icon: 'Replace',
    featureId: 'source-text',
    layout: 'standard',
    width: 300,
    height: 220,
    minWidth: 240,
    minHeight: 180,
    executable: true,
  },
  bp: {
    title: 'BP 模板',
    icon: 'LayoutTemplate',
    featureId: 'creative-library',
    layout: 'wide',
    width: 360,
    height: 300,
    minWidth: 280,
    minHeight: 220,
    executable: true,
  },
  'frame-extractor': {
    title: '帧提取',
    icon: 'Camera',
    featureId: 'source-media',
    layout: 'standard',
    width: 360,
    height: 320,
    minWidth: 280,
    minHeight: 240,
    executable: true,
  },
  combine: {
    title: '组合',
    icon: 'Combine',
    featureId: 'canvas',
    layout: 'compact',
    width: 240,
    height: 120,
    minWidth: 180,
    minHeight: 80,
    executable: false,
  },
};

/** 获取节点渲染元信息 */
export function getNodeRendererMeta(nodeType: NodeType): NodeRendererMeta {
  return NODE_RENDERER_REGISTRY[nodeType] || {
    title: nodeType,
    icon: 'Box',
    featureId: 'canvas',
    layout: 'compact',
    width: 300,
    height: 200,
    minWidth: 180,
    minHeight: 100,
    executable: false,
  };
}

/** 检查节点类型是否已注册 */
export function isNodeRendererRegistered(nodeType: NodeType): boolean {
  return nodeType in NODE_RENDERER_REGISTRY;
}
